name:  Hello World Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  hello:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello World12"
        shell: bash
  goodbye:
    runs-on: self-hosted
    steps:
      - name: goodbye world
        run: echo "goodbye world12"
        shell: bash