name: Create a comment on a new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump ubuntu context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment with community
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: "+1"
  comment-with-api:
    runs-on: self-hosted
    steps:
      - name: Create comment with api
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${PAT_TOKEN}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "${URL}" \
          -d '{"body":"Test Comment from api"}'
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          URL: ${{ github.event.issue.comments_url }}